2022-01-15 00:33:58,178 <ERROR> :  occered at executeGetRequest <class 'ValueError'>1
2022-01-15 00:33:58,178 <ERROR> : Traceback (most recent call last):
  File "./py/connect.py", line 194, in executeGetRequest
    root = lxml.html.fromstring(html)
  File "C:\Users\waard\Desktop\my-app\py\env_v3.8.12\lib\site-packages\lxml\html\__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "C:\Users\waard\Desktop\my-app\py\env_v3.8.12\lib\site-packages\lxml\html\__init__.py", line 761, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "src\lxml\etree.pyx", line 3252, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1907, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

